name: imp_router
description: "Imperative navigation using flutter's Router, to overcome limitations of the plain Navigator."
version: 0.1.0
repository: https://github.com/martinsellergren/imp_router
issue_tracker: https://github.com/martinsellergren/imp_router/issues
topics:
  - imp_router
  - router
  - navigator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  collection: ^1.18.0
  provider: ^6.1.1
  rxdart: ^0.27.7
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
